<a href="https://colab.research.google.com/github/chstruppix/M-TMHC/blob/main/(main)_M_TMHC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import categorical_crossentropy
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.layers import Dense
 
from numpy import argmax
import re

In [2]:
X = ['Depressed',
     'sad',
     'life sucks',
     'time alone',
     'lifes bad',
     'uncontrollable',
     'anxious',
     'wrestless',
     'nervous',
     'out of control',
     'incapable',
     'unworthy',
     'underwhelmed',
     'incompetent',
     'directionless',
     'tension',
     'stressed',
     'worried',
     'strained',
     'burdened']
len(X)

20

In [3]:
Y = ['depressed',
     'depressed',
     'depressed',
     'depressed',
     'depressed',
     'anxious',
     'anxious',
     'anxious',
     'anxious',
     'anxious',
     'demotivated',
     'demotivated',
     'demotivated',
     'demotivated',
     'demotivated',
     'stressed',
     'stressed',
     'stressed',
     'stressed',
     'stressed']
len(Y)

20

In [4]:
def remove_non_alpha_numeric_characters(sentence):
    new_sentence = ''
    for token in sentence:
        if token.isalpha() or token == ' ':
            new_sentence += token
    return new_sentence

In [5]:
def preprocess_data(X):
    X = [data_point.lower() for data_point in X]
    X = [remove_non_alpha_numeric_characters(
        sentence) for sentence in X]
    X = [data_point.strip() for data_point in X]
    X = [re.sub(' +', ' ',
                data_point) for data_point in X]
    return X

In [9]:
X = preprocess_data(X)

vocabulary = set()
for data_point in X:
        vocabulary.add(data_point)


vocabulary = list(vocabulary)
print(vocabulary)
print(len(vocabulary))

['uncontrollable', 'stressed', 'tension', 'underwhelmed', 'depressed', 'unworthy', 'incompetent', 'burdened', 'wrestless', 'life sucks', 'directionless', 'time alone', 'sad', 'worried', 'incapable', 'anxious', 'lifes bad', 'strained', 'out of control', 'nervous']
20


In [14]:
X_encoded = []

def encode_sentence(sentence):
    sentence = preprocess_data([sentence])[0]
    print(sentence)
    print('\n' + 'sep' + '\n')
    # print(preprocess_data([sentence]))
    # print(preprocess_data([sentence])[0])
    sentence_encoded = [0] * len(vocabulary)
    for i in range(len(vocabulary)):
        if vocabulary[i] in sentence.split(' '):
            sentence_encoded[i] = 1
    return sentence_encoded

X_encoded = [encode_sentence(sentence) for sentence in X]
print(X_encoded)

depressed

sep

sad

sep

life sucks

sep

time alone

sep

lifes bad

sep

uncontrollable

sep

anxious

sep

wrestless

sep

nervous

sep

out of control

sep

incapable

sep

unworthy

sep

underwhelmed

sep

incompetent

sep

directionless

sep

tension

sep

stressed

sep

worried

sep

strained

sep

burdened

sep

[[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0

In [15]:
classes = list(set(Y))
print(classes)
Y_encoded = []
for data_point in Y:
    data_point_encoded = [0] * len(classes)
    for i in range(len(classes)):
        if classes[i] == data_point:
            data_point_encoded[i] = 1
    Y_encoded.append(data_point_encoded)

print(Y_encoded)

['anxious', 'depressed', 'stressed', 'demotivated']
[[0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0]]


In [16]:
X_train = X_encoded
y_train = Y_encoded
X_test = X_encoded
y_test = Y_encoded

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_encoded,Y_encoded, train_size=0.8, random_state=123, shuffle=True)

In [18]:
model = Sequential()
model.add(Dense(units=64, activation='sigmoid',
                input_dim=len(X_train[0])))
model.add(Dense(units=len(y_train[0]), activation='softmax'))
model.compile(loss=categorical_crossentropy,
              optimizer=SGD(lr=0.09,
                            momentum=0.45, nesterov=True))

model.fit(np.array(X_train), np.array(y_train), epochs=200, batch_size=1)

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


Epoch 1/200
16/16 [==============================] - 1s 2ms/step - loss: 2.0948
Epoch 2/200
16/16 [==============================] - 0s 2ms/step - loss: 1.9521
Epoch 3/200
16/16 [==============================] - 0s 2ms/step - loss: 2.2436
Epoch 4/200
16/16 [==============================] - 0s 1ms/step - loss: 1.8010
Epoch 5/200
16/16 [==============================] - 0s 2ms/step - loss: 1.9912
Epoch 6/200
16/16 [==============================] - 0s 2ms/step - loss: 1.8680
Epoch 7/200
16/16 [==============================] - 0s 2ms/step - loss: 1.9261
Epoch 8/200
16/16 [==============================] - 0s 1ms/step - loss: 1.8239
Epoch 9/200
16/16 [==============================] - 0s 2ms/step - loss: 1.7531
Epoch 10/200
16/16 [==============================] - 0s 2ms/step - loss: 1.7423
Epoch 11/200
16/16 [==============================] - 0s 2ms/step - loss: 1.7152
Epoch 12/200
16/16 [==============================] - 0s 2ms/step - loss: 1.5938
Epoch 13/200
16/16 [=================

In [19]:
!pip install ann_visualizer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for ann_visualizer: filename=ann_visualizer-2.5-py3-none-any.whl size=4168 sha256=17c165dfd8c1791765199d69b4090895e0a058a7c953291445fb5c4d8751db52
  Stored in directory: /root/.cache/pip/wheels/4b/ef/77/9b8c4ae2f9a11de19957b80bc5c684accd99114bb8dc6b374c
Successfully built ann_visualizer


In [20]:
from ann_visualizer.visualize import ann_viz
ann_viz(model, title="Nueral Network for chatbot")

In [21]:
predicted_value = model.predict(np.array(X_test))
predictions = [argmax(pred) for pred in model.predict(np.array(X_test))]
print("The predicted value is", predicted_value)
print("The predicted value using argmax is", predictions)
print("The actual value is", y_test)

1/1 [==============================] - 0s 49ms/step
The predicted value is [[0.1586396  0.8096178  0.0158098  0.01593282]
 [0.13019219 0.8451836  0.01443123 0.01019291]
 [0.13723345 0.8406302  0.01090408 0.01123232]
 [0.15344411 0.8151238  0.01652386 0.01490816]]
The predicted value using argmax is [1, 1, 1, 1]
The actual value is [[0, 0, 0, 1], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0]]


In [22]:
correct = 0
for i in range(len(predictions)):
    if predictions[i] == argmax(y_test[i]):
        correct += 1

print ("Correct:", correct)
print ("Total:", len(predictions))

Correct: 1
Total: 4


In [23]:
first_conversation = input('''Hey! This is Maya, your mental health assistant. I'm here to serve you, as a friend, teacher and guru. 
I want you to be completely open with me and for you to speak your heart out.
You can use me as a journal, as a friend who just listens and never speaks, one who never judges and one who never betrays.
You can be terribly honest with me and I won't complain about it to anyone, be it some close relative you're bitching about or a decision you made early on in your life and regret the same.
Really, you can tell me anything and it will remain to yourself, though I'll be listening and would
want to recommend you some ways to improve on your health. Please, stay safe and calm and always know that no matter what happens, you should
not give up and never be afraid to try. We haven't been brought to this world for any reason, and we all have our own destinies.
As you can see, I speak too much :)
But, I'd want to asure you that sometimes, it's not a bad thing to speak too much. In fact, there are thousands of people like me, who spend hours writing in journals,
because written words have more power than spoken ones.
+
With that, I'd like to take our conversation further and maybe include you to help me convert this one-sided conversation to a healthy interaction.

I want you to pen down all your thoughts; everything that comes to your mind when you think about yourself. Everything, I want you to be as open
to me as you are or want to be with yourself. \n\n''')
while len(first_conversation) < 100:
  first_conversation = first_conversation + input('''You're doing extremely well, but I can notice that you are somewhat shy. 
  I'd want you to be as open as possible. Please consider this as a humble request and continue writing.\n\n''')
second_conversation = input('''Good job! You really did it! How do you feel now? You must be feeling much better, to let it all out for once.
If you, however, still feel the same, or perhaps worse, please debrief in 2-3 words on how you feel: ''')
    
prediction= model.predict(np.array([encode_sentence(second_conversation)]))
pred_class = classes[argmax(prediction)]
if pred_class == 'stressed':
  response1 = input('''I think that you are feeling stressed. No worries, though, (ironic!) I'm here to help! 
  You should try to take some rest, relax and spend time on things that you enjoy. 
  Whether that's playing video games, binging Netflix, or reading books.
  Meditating is a great remedy and will do wonders if you try. 
  If you'd like, I can recommend you some funny videos from Youtube that you may watch.
  Also, I can provide you a list of great stress-busting slow tunes that may help you feel better.
      
  Press 'y' for youtube videos and 's' for slow, relaxing tunes.\n''')
  response1 = response1.lower()
  if response1 == 'y':
    print('''https://www.youtube.com/watch?v=acPAFyohdk0
    https://www.youtube.com/watch?v=UERyZTmDKkw \n''')
  elif response1 == 's':
    print('''https://www.youtube.com/watch?v=OCGiW4_zrfA
    https://www.youtube.com/watch?v=JLJqUipWRWk \n''')
  else:
    print('''ALright, please stay calm and motivated, there's just so much of 'you' left in you waiting to be discovered, 
    that there's no point in giving up! Please feel free to talk to me again if you need any more help because I love to help people like you!!''')
elif pred_class == 'demotivated':
  response2 = input('''It feels like you're feeling demotivated. Ain't no worries, though! I can help you stay motivated by recommending you some great motivational videos
  or I can provide you with a list of motivational songs! 
  
  Press 'y' for youtube videos and 's' for nice, motivational tunes/songs.\n''')
  response2 = response2.lower()
  if response2 == 'y':
    print('''https://www.youtube.com/watch?v=83RUhxsfLWs
    https://www.youtube.com/watch?v=OUFuaMj6z-w \n''')
  elif response2 == 's':
    print('''https://www.youtube.com/watch?v=OCGiW4_zrfA
    https://www.youtube.com/watch?v=JLJqUipWRWk \n''')
elif pred_class == 'anxious':
  response3 = input('''It seems like you're feeling anxious, which is completely normal and there's nothing to worry about. Tens of millions of people face
  anxiety and most of them do just fine! You'll do too, believe me! 
  To help you feel relaxed and composed, I can recommend you some calm and relaxing youtube videos or tunes!
  
  Press 'y' for youtube videos and 's' for calm, relaxing tunes that you can vibe to!''')
  response3 = response3.lower()
  if response3 == 'y':
    print('''https://www.youtube.com/watch?v=2OEL4P1Rz04
    https://www.youtube.com/watch?v=79kpoGF8KWU \n''')
  if response3 == 's':
    print('''https://www.youtube.com/watch?v=PcuY147VpnM
    https://www.youtube.com/watch?v=IvdahN23rQ0 \n''')
elif pred_class == 'depressed':
  response4 = input('''I have a feeling that you're depressed. Nothing to feel bad about though, hundreds of millions of people have it around the world!
  All I would recommend you to do is to meditate, spend time on hobbies (try developing some if you have none!) or stay busy (occupied)!
  I do, however, know some great Youtube videos and vibe-y songs that might help you feel better!
  
  Press 'y' for youtube videos or 's' for nice, feel-good tunes\n''')
  response4 = response4.lower()
  if response4 == 'y':
    print('''https://www.youtube.com/watch?v=BNiTVsAlzlc
    https://www.youtube.com/watch?v=9LhLjpsstPY \n''')
  if response4 == 's':
    print('''https://www.youtube.com/watch?v=QZQeie2iY7E
    https://www.youtube.com/watch?v=EZpJMP4YdXE \n''')


  



    
    


Hey! This is Maya, your mental health assistant. I'm here to serve you, as a friend, teacher and guru. 
I want you to be completely open with me and for you to speak your heart out.
You can use me as a journal, as a friend who just listens and never speaks, one who never judges and one who never betrays.
You can be terribly honest with me and I won't complain about it to anyone, be it some close relative you're bitching about or a decision you made early on in your life and regret the same.
Really, you can tell me anything and it will remain to yourself, though I'll be listening and would
want to recommend you some ways to improve on your health. Please, stay safe and calm and always know that no matter what happens, you should
not give up and never be afraid to try. We haven't been brought to this world for any reason, and we all have our own destinies.
As you can see, I speak too much :)
But, I'd want to asure you that sometimes, it's not a bad thing to speak too much. In fact, there